CATEGORY_NAME = [
                "450977006|Results reference set for GP/FP reason for encounter#763288003|patient review#185349003|encounter for check up",
                 "33879002|Active immunisation",
                 "275498002|Respiratory tract infection",
                 "417163006|Traumatic AND/OR non-traumatic injury#106028002|Musculoskeletal finding",
                 "21522001|Abdominal pain",
                 "22253000|pain",
                 "14760008|Constipation",
                 "118235002|Eye / vision finding",
                 "297268004|Ear, nose and throat finding#302775008|Ear, nose and throat tests",
                 "195967001|Asthma#473011001|Allergic condition",
                 "95320005|Disorder of skin",
                 "74732009|Mental illness#162314006|Harmful thoughts#225481000|Abusive behaviour",
                 "248842004|Female genitalia finding#89164003|breast lump",
                 "235595009|Gastroesophageal reflux disease#9991008|Abdominal colic",
                 "314938000|Poor sleep pattern#248330001|General growth finding#271795006|Malaise and fatigue#271737000|Anaemia#35240004|Iron deficiency#414916001|Obesity",
                 "40733004|Infection",
                 "5294002|Development disorder"
]

CATEGORY_NAME_MAP = {
                "450977006|Results reference set for GP/FP reason for encounter#763288003|patient review#185349003|encounter for check up": "Results / Plans",
                 "33879002|Active immunisation": "Immunisation",
                 "275498002|Respiratory tract infection" :"Infection- Resp",
                 "417163006|Traumatic AND/OR non-traumatic injury#106028002|Musculoskeletal finding": "Injury / Musculoskeletal",
                 "21522001|Abdominal pain" : "Abdominal pain",
                 "22253000|pain":"Pain syndrome",
                 "14760008|Constipation" : "Constipation / Bowels",
                 "118235002|Eye / vision finding" : "Ophthalmology",
                 "297268004|Ear, nose and throat finding#302775008|Ear, nose and throat tests": "ENT - other",
                 "195967001|Asthma#473011001|Allergic condition" : "Asthma and Allergy",
                 "95320005|Disorder of skin" : "Dermatology",
                 "74732009|Mental illness#162314006|Harmful thoughts#225481000|Abusive behaviour" : "Mental Health",
                 "248842004|Female genitalia finding#89164003|breast lump" :"Gynae.",
                 "235595009|Gastroesophageal reflux disease#9991008|Abdominal colic" : "Reflux / Colic",
                 "314938000|Poor sleep pattern#248330001|General growth finding#271795006|Malaise and fatigue#271737000|Anaemia#35240004|Iron deficiency#414916001|Obesity" : "Constitutional",
                 "40733004|Infection": "Infection- other",
                 "5294002|Development disorder" : "Developmental / Behavioural"
}

# CATEGORY_NAME = ["297268004|Ear, nose and throat finding#302775008|Ear, nose and throat tests"]

CHECK_LIST = ["review", "plan", "investigation", "action"]

LOW_THRESHOLD = 0.85
HIGH_THRESHOLD = 0.90

MATCHED_SCORE = 1
DIRECT_MATCHED_SCORE = 0.5
BEST_SCORE = 666
THRESHOLD = 10




SEEN_UNSEEN = ["URTI",
"Viral illness",
"Immunisation",
"Review",
" viral",
"Asthma",
"Vaccination",
"Croup",
"Tonsillitis",
"Results discussed",
"Gastroenteritis",
"viral URTI",
"Abdominal pain",
"Viral URTI",
"Cough",
"Anxiety",
"Eczema",
"Referral letter",
"Rash",
"Wart cryotherapy",
"Head injury",
"Otitis media",
"Constipation",
"Impetigo",
"Travel advice",
"Conjunctivitis",
"Cryotherapy",
"Check up",
"LRTI",
"UTI",
"Acne",
"Asthma action plan",
"Fever",
"Script",
"Vomiting",
"Depression",
"Mental health care plan",
"URTI - Viral",
"Sore throat",
"cough",
"Wound review",
" Eczema",
"Molluscum contagiosum",
"12/12 immunisation",
"Otitis externa",
"Skin infection",
" URTI",
"Allergy",
"result",
"Behaviour problem",
"Ear pain",
"Finger injury",
"Iron deficiency",
" Results discussed",
"Bronchiolitis",
"Headache",
"Knee pain",
"Pharyngitis",
"review",
"Warts",
"Wound care",
"",
" Asthma",
" Wart",
"6/12 immunisation",
"6/52 neonatal check",
"Ear check",
"Tiredness",
"Travel vaccination",
"Wart",
" bacterial",
" Croup",
" OCP",
" Vaccination",
"ADHD",
"Ankle injury",
"Chest infection",
"Chickenpox",
"Diarrhoea",
"Laceration",
"Otitis Media",
"Sinusitis",
"Balanitis",
"Fall",
"Skin lesion",
"Wheezing",
" Immunisation",
" URTI  Viral",
"Back pain",
"Cellulitis",
"Croupy cough",
"GP Management Plan",
"Ingrown toenail",
"Knee injury",
"Medical certificate",
"Nose injury",
"otitis media",
"Post Natal Check",
"Tonsillitis - bacterial",
"URTI  Viral",
"Wrist injury",
" Follow up",
" Referral letter",
" Review",
"Autism spectrum disorder",
"Contraception",
"Dermatitis",
"Immunisation advice",
"Insect bite",
"Oral contraceptive",
"Plantar wart",
"Urticaria",
"Viral infection",
"Wound",
" Acne",
" Advice and listening",
" Asthma action plan",
" Cryotherapy",
" Mental health care plan",
" Patient education",
"Anxiety disorder",
"Contraceptive advice",
"Diarrhea",
"fever",
"Follow up",
"Foot pain",
"GORD",
"GP Mental Health Care Plan",
"Letter written",
"Paronychia",
"Review of results",
"Wart(s)",
"Wheeze associated with respiratory infection",
"Wound check",
" 6/52 neonatal check",
" Anxiety",
" child",
" Gastroenteritis",
" nocturnal",
" Rash",
"4/12 immunisation",
"6/52 immunisation",
"Abscess",
"Allergic conjunctivitis",
"Anxiety/Depression",
"constipation",
"Elbow injury",
"Epistaxis",
"Health check",
"Hip pain",
"Laceration repair",
"Rhinitis",
"School sores",
"Thrush",
"Unwell",
" childhood",
" common",
" Depression",
" infrequent episodic",
" Plantar wart",
" soft tissue",
" Viral illness",
" Warts",
"18/12 immunisation",
"Advice and listening",
"Bedwetting",
"Cold",
"Concussion",
"Desensitisation injection",
"Dysuria",
"File review",
"Follow up of results",
"Foot injury",
"Fracture",
"Hand injury",
"Hay fever",
"Ingrowing toenail",
"Injury",
"Insomnia",
"Left Otitis media",
"Left Wrist injury",
"Major depression",
"Mental Health Care Plan - Preparation",
"Mental health consult",
"Migraine",
"New patient",
"Otitis Externa",
"Paperwork",
"Perioral dermatitis",
"rash",
"Results given",
"script",
"Thumb injury",
"Toe injury",
"vaccination",
"Vaccination advice",
"Viral exanthem",
"Well Infant Checkup",
"Wound dressing",
" Abdominal pain",
" asthma",
" Cellulitis",
" central",
" Constipation",
" foot and mouth disease",
" GP Mental Health Care Plan",
" Headache",
" Meningococcus",
" Molluscum contagiosum",
" Referral to paediatrician",
" skin",
" Vomiting",
" Well Infant Checkup",
" Wheezing",
"4 year immunisation",
"6 month check & vaccination",
"Abdominal cramps",
"Anaphylaxis",
"Ankle sprain",
"Arm injury",
"asthma",
"Bite",
"Boil",
"Bronchiolitis/ review",
"Bronchitis",
"Burn",
"Care plan preparation",
"Eustachian tube dysfunction",
"Fatigue",
"Febrile illness",
"Foreign body in skin",
"Hand",
"Humeral fracture",
"Lip swollen",
"multiple issues",
"Nappy rash",
"Nausea",
"Palpitations",
"Pathology request form",
"Plagiocephaly",
"PUO",
"Red eye",
"Right Otitis media",
"Right Otitis Media",
"Ringworm",
"Soft tissue injury",
"sore throat",
"Spirometry",
"Stye",
"Teething",
"tonsillitis",
"Urinary tract infection",
"URTI Viral",
"Viral rash",
"vomiting",
"Weight check",
"Wound infection",
" Abrasion",
" Allergy",
" anxiety",
" Back pain",
" Care plan preparation",
" Contraception",
" Dysmenorrhoea",
" Fatigue",
" gastrooesophageal",
" Insect bite",
" Menorrhagia",
" Otitis media",
" Perioral dermatitis",
" recurrent",
" Results discussed with patient",
" Script",
" serous",
" Sore throat",
" suppurative",
" Tonsillitis",
" URTI - Viral",
" Urticaria",
" Wart cryotherapy",
" Wound care",
"abdominal pain",
"Acne - pustular",
"allergic rhinits",
"anaphylaxis action plan",
"anxiety",
"Anxiety",
"asthma exacerbation",
"Bilateral Otitis Media",
"Care plan",
"Care plan review",
"Circumcision",
"Coeliac disease",
"Cough - post viral",
"Cyst",
"Dehydration",
"dermatitis",
"Dysmenorrhoea",
"ear review",
"Ear wax",
"Eczema - atopic",
"Enuresis",
"Eye check",
"Foreign body in nostril",
"Forms",
"Gastritis",
"GP Management Plan review",
"Immunisation 18 m",
"Immunisation enquiry",
"impetigo",
"Infected wound",
"Ingrown toenail infection",
"Iron deficiency anaemia",
"Left Ankle injury",
"Left Ear pain",
"Lymphadenitis",
"Menorrhagia",
"MVA",
"Nasal obstruction",
"not seen",
"Oral Contraceptive Pill prescription",
"otitis externa",
"Pneumonia",
"Post infective cough",
"Post operative review",
"Pulled elbow",
"Rash in groin",
"Rash on face",
"Referral",
"Referral - Letter Written",
"Reflux",
"Respiratory tract infection",
"Results follow up.",
"Rhinosinusitis",
"Right Ear effusion",
"Runny nose",
"Shoulder pain",
"Skin check",
"Tic disorder",
"Travel Advice",
"UTI (Urinary Tract Infection)",
"Vaginal discharge",
"viral gastritis",
"wart",
"Worms",
"Wrist pain",
" ? ? Roseola infantum",
" 6/52 immunisation",
" action plan",
" ADHD",
" adolescent",
" allergic reaction",
" Allergic Rhinitis",
" Anger",
" Autism spectrum disorder",
" Conjunctivitis",
" Contraceptive advice",
" cough",
" Cough",
" Dermatitis",
" Dyslexia",
" Ear check",
" eczema",
" Eczema  infected",
" Fall",
" Febrile convulsions",
" Folliculitis",
" Forearm injury",
" GIT sx",
" GP Mental Health Care Plan review",
" Hay fever",
" Hepatitis A",
" Immunisation advice",
" Impetigo",
" infective exacerbation",
" Influenza Immunisation",
" Insomnia",
" iron deficiency",
" laparoscopic",
" Letter written",
" LRTI",
" lumbosacral",
" Mental Health Care Plan - Preparation",
" Nausea",
" occipital",
" oral",
" Otitis Media",
" Paronychia",
" Pathology request form",
" plantar",
" Plaster application",
" Prescription renewal",
" PTSD",
" reduction",
" Repeat prescription",
" Results follow up.",
" Right Otitis Media",
" rotavirus",
" School problems",
" separation",
" Sleep disorder",
" Sleeping difficulty",
" Teething",
" Tonsillectomy/Adenoidectomy",
" Travel advice",
" Urti",
" Vaccination advice",
" viral",
" Viral URTI",
" Weight check",
"12 months immunisation",
"4 month check & vaccination",
"6 week check",
"6 weeks review",
"abdo pain",
"Abdominal pain - Acute",
"Abrasion",
"Allergic dermatitis",
"Ankle pain",
"ankle sprain",
"Aphthous ulcers",
"Asthma",
"Asthma - infective exacerbation",
"Asthma exacerbation",
"Asthma review",
"Autistic disorder",
"Baby check",
"Behaviour problem - Child",
"Bilateral Epistaxis",
"Bilateral Otitis media",
"BP Check",
"Bruise",
"Cast removal and replaced",
"Cellulitis - Leg",
"Chlamydia Infection",
"Colic - Infant",
"Conjunctivitis - allergic",
"Conjunctivitis - bacterial",
"Contact dermatitis",
"Contusion on right sole",
"Counselling",
"croupy cough",
"Depot contraception",
"Depression/Anxiety",
"Dermatology referral",
"Dizziness",
"Dressing change",
"Dry Eyes",
"Ear effusion",
"ear pain",
"Eczema  atopic",
"Epigastric discomfort",
"eyelid swelling",
"Folliculitis",
"Forearm injury",
"Foreign body",
"FTA - failed to attend",
"GP Mental Health Care Plan review",
"green faeces",
"Grief counselling",
"Grief reaction",
"Groin pain",
"Growth delay",
"Head injury minor",
"Head lice",
"Hearing - Impaired",
"Hearing test",
"Heel pain",
"Hepatitis A immunisation",
"Humira injection",
"Hydronephrosis",
"immunisation",
"Immunisation",
"Immunisation 4 yr",
"immunisation catch up",
"Implanon review",
"Infected skin lesion",
"Infective exacerbation of asthma",
"Ingrowing nail",
"Injured finger",
"insect bite",
"Insect bite allergy",
"Intellectual disability",
"Irregular periods",
"laceration",
"Left Conjunctivitis",
"Left Knee injury",
"Left Otitis Media",
"lethargy",
"Lethargy",
"Letter faxed",
"Loose stools",
"LUTS",
"Lymph gland swelling",
"medical review",
"Mental health care plan review",
"Migraine with aura",
"Mosquito bite",
"Mouth ulcer",
"Muscle pain",
"Nappy rash - candidal",
"Nasal blockage",
"nausea",
"Nose pain",
"Osgood-Schlatter disease",
"Pathology Referral",
"Patient education",
"Pelvic pain",
"Periorbital cellulitis",
"Plantar warts",
"Post surgical review",
"Prescription",
"Prescription renewal",
"Preseptal cellulitis",
"Radiology request form",
"referral letter",
"Referral to paediatrician",
"Reflux oesophagitis",
"Removal of sutures",
"Repeat prescription",
"Results discussed with patient",
"review pathology",
"Right Ankle sprain",
"Right Dermatitis",
"Right Ear pain",
"Right Foot pain",
"Right Forearm injury",
"Right Hand injury",
"Right Knee pain",
"Right Otitis externa",
"Right Plantar wart",
"Right Shoulder pain",
"right wrist pain",
"ROS",
"Roseola infantum",
"Sever's disease",
"skin infection",
"Sleep disorder",
"Sleep disturbance",
"Snapping hip syndrome",
"Speech abnormality",
"Splinter",
"staph nasal infection",
"Staphylococcal infection",
"Streptococcal pharyngitis",
"Stuttering",
"Suture removal",
"Swollen lip",
"Tendonitis",
"Throat pain",
"Thumb pain",
"Tinea",
"Tinea pedis infection",
"Toe pain",
"Typhoid Immunisation",
"Upper respiratory tract noise",
"Urinary frequency",
"Urti",
"UTI - recurrent",
"Vaccination  12 month",
"vaccination Bexsero",
"Varicocoele",
"Viral croup",
"viral Exanthems",
"viral gastroenteritis",
"Viral gastroenteritis",
"Viral illness",
"viral urti",
"Vulval pruritus",
"Vulvo-vaginitis",
"Vulvo-vaginitis (nonspecific)",
"Wart cryotherapy",
"Wax - Ear",
"Wrist fracture",
"  blood form",
"  viral",
" ? ? Asthma",
" ?roseola?uti",
" 18/12 immunisation",
" 6 month check & vaccination",
" 6 month check up",
" 6 weeks check up",
" 6/12 immunisation",
" Abscess",
" Achilles tendon injury",
" acne",
" Acupuncture",
" acute",
" ADT",
" Allergic dermatitis",
" allergy action plan",
" Allergy to eggs",
" Amenorrhoea",
" Anal pain",
" Ankle sprain",
" ant",
" Anxiety disorder",
" Anxiety/Depression",
" Anxious",
" Asthma  Chronic Persistent",
" atopic",
" Behaviour problem",
" Big toe",
" Bilateral Ear pain",
" Bilateral Otitis Media",
" Blister",
" Boil",
" Bowel habit  Change",
" Breast pain",
" Bronchiolitis",
" Bruise",
" Bruising",
" Candidal",
" Chest injury",
" chest trauma",
" chronic",
" classical",
" Coeliac disease",
" Colic",
" comedonal",
" Concussion",
" croup",
" CRPS",
" cryotherapy",
" cystic",
" Dehydration/ mild",
" Dermatitis - Allergic",
" Dermatitis - Atopic",
" Dermatofibroma",
" developmental",
" Developmental delay",
" diarrhea",
" Diarrhea",
" diarrhoea",
" Disturbed family",
" Dressing change",
" Drug abuse",
" Drug reaction",
" Dysuria",
" Ear infection",
" Ear pain",
" Eating Disorder",
" egg",
" Encopresis",
" Enuresis",
" EPC",
" Epilepsy",
" epistaxis",
" Exertional dyspnoea",
" Eye check",
" Failure to thrive",
" Fall from horse",
" Febrile illness",
" Fever",
" FH Brugada Sy causing sudden cardiac death",
" Fibular fracture",
" Financial problems",
" Finger injury",
" Finger sprain",
" Fissure - Anal",
" Flat feet",
" follow up",
" Follow up of results",
" Foreign body",
" Fracture - Toe",
" Fractured distal radius",
" Fractured forearm",
" Fussy eater",
" Gait abnormal",
" Ganglion",
" GOR (Gastrooesophageal Reflux)",
" GORD (Gastro-oesophageal Reflux Disease)",
" GORD (Gastrooesophageal Reflux Disease)",
" Graze",
" Grommet",
" Grommet insertion",
" Growth retardation",
" Hand injury",
" Head injury",
" headache)",
" headaches",
" Hepatitis A immunisation",
" hip abnormality",
" Hip dysplasia",
" Home visit",
" Hordeolum",
" HPV",
" HPV",
" HPV and Boostrix",
" HPV immunisation",
" Hydrocoele",
" immunisation",
" Immunisation - 2 month",
" Indigestion",
" infeccted",
" Inflammatory Acne",
" insomnia",
" Iron deficiency",
" knee",
" Knee injury",
" Laceration",
" Left Otitis media",
" leg",
" Lethargy",
" Letter read",
" Lip swollen",
" Liquid N2 Cryotherapy - Solar keratosis",
" Loose stools",
" low iron",
" Lymph node check",
" Malaise",
" Mastoiditis",
" maxillary",
" MEASLES",
" Medial collateral ligament of knee sprain",
" Medical certificate",
" Medical Imaging",
" Meibomian abscess (chalazion)",
" mental health",
" Mental health consult",
" Mesenteric adenitis",
" Migraine",
" mild",
" Mild Eczema",
" Milk",
" Mole check",
" mosquito",
" Muscle pain",
" Nappy rash",
" Nappy rash - candidal",
" Nasal mucosal inflammation",
" Nebulisation",
" Neck swelling",
" Neurology referral",
" Nightmares",
" Nocturnal enuresis",
" Nocturnal enuresis",
" Nosebleed",
" Obesity",
" OCD (Obsessive Compulsive Disorder)",
" Oral Contraceptive Pill prescription",
" Osgood Schlatter disease",
" otitis externa",
" Otitis externa",
" Otitis Externa",
" otitis media",
" Paediatrician referral",
" Pain",
" painful",
" Paperwork",
" papular",
" Parental anxiety",
" paroxysmal",
" Pathology Referral",
" Peanut allergy",
" peanut allergy IgE mediated",
" pelvic pain",
" Pelvic pain",
" Perforated tympanic membrane",
" Periorbital cellulitis",
" PID (Pelvic inflammatory disease)",
" PND",
" PND (Post Nasal Drip)",
" Positional head deformity",
" post infective",
" post infective",
" Post operative care",
" Post viral cough",
" Prescription",
" primary",
" Rabies",
" Reactive lymphadenopathy",
" Recurrent",
" Referral",
" Referral - Letter Written",
" Referral to dermatologist",
" Referral to ENT surgeon",
" referral to out patient pediatrician",
" Referral to psychologist",
" Repeat scripts",
" Results review",
" Retractile testis",
" review",
" Review medication",
" Review of Team Care Arrangement",
" Rhinitis",
" Right Chondromalacia Patella",
" Right Intoeing",
" Right Orchidopexy",
" Right Trigger Thumb",
" ringworm",
" Ringworm",
" Scalp psoriasis",
" script",
" Seborrhoeic keratosis/es",
" Self harm",
" Shortness of breath",
" Shoulder injury",
" Sinusitis",
" Skin infection",
" skin/ thumb",
" Slow to gain weight",
" smoker",
" sore throat",
" Speech  Delay",
" Speech abnormality",
" Speech concerns",
" Speech difficulty",
" Starvation",
" stress",
" stress)",
" Stuttering",
" subcutaneous",
" superficial partial thickness",
" Suture of skin laceration",
" Team Care Arrangement review",
" Tendinitis",
" Thrush",
" thumb injury",
" Thumb injury",
" Tic",
" Tic disorder",
" Tiredness",
" TMJ Dysfunction",
" Tonsillar abscess",
" Travel Advice",
" Typhoid",
" Unwell (dizzy",
" urinary",
" Urinary frequency",
" Urinary urgency",
" urine",
" URTI  Viral with wheeze",
" URTI Viral",
" UTI (Urinary Tract Infection)",
" vaccination",
" vaginal",
" Vegan",
" Viral croup",
" Viral illness  Non specific",
" Viral illness non specific",
" Viral pharyngitis",
" Viral wart",
" viral/ review",
" Vomiting  cause unknown",
" VSD",
" Wax in ear",
" Weight reduction management",
" Well Infant Check-up",
" Wheals",
" Whooping cough",
" Wound",
" Wrist pain",
"(1) Paronychia (2) Mild R OM",
"? ? Pelvic inflammatory disease",
"? ? Roseola infantum",
"? asthma",
"? Coeliac disease",
"??asd",
"?ASD",
"?coeliac disease",
"?Exercise induced asthma",
"?Hearing impaired",
"?hypomelanosis of Ito",
"?otitis media",
"?scaphoid fracture",
"12 month check & vaccination",
"12m vaccinations",
"18 month immuisation",
"18 months immunisation",
"4 month immu",
"4 month vaccines",
"4 months immunisation",
"4 year old health assesment",
"4 years immunisation",
"4/12 Immunisation",
"4y immunisation",
"6 week check up"]